name: 'Create Monorepo Release PR'
description: 'Bump monorepo package versions and create a release PR.'
inputs:
  release-type:
    description: 'A SemVer version diff, i.e. major, minor, patch, prerelease etc. Mutually exclusive with "release-version".'
    required: false
  release-version:
    description: 'A specific version to bump to. Mutually exclusive with "release-type".'
    required: false
runs:
  using: 'composite'
  steps:
    - id: update-packages
      run: node $GITHUB_ACTION_PATH/dist/index.js
      shell: bash
    - id: create-release-pr
      run: $GITHUB_ACTION_PATH/src/create-release-pr.sh ${{ steps.update-packages.outputs.NEW_VERSION }}
      shell: bash
