name: "Tests"
on: push

jobs:
  # linting and unit tests
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --ignore-scripts
      - run: yarn build
      - run: yarn lint
      - run: yarn test

  # action-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  #       with:
  #         milliseconds: 1000
